import { asset, personalOrderUrl } from "./site";

export const products = [
  {
    id: "escuridao-absoluta",
    featured: true,
    name: "Escuridão Absoluta",
    line: "Display / box — Mega Evolução",
    detail: "Caixa display com boosters da coleção Mega Evolução (Darkrai na arte).",
    alt: "Caixa display Escuridão Absoluta Mega Evolução com boosters e arte do Darkrai",
    src: asset("produtos/escuridao-absoluta-cut.png"),
    orderLabel: "Display Escuridão Absoluta — Mega Evolução",
  },
  {
    id: "treinador-avancado",
    featured: false,
    name: "Coleção Treinador Avançado",
    line: "Megaevolução: Caos Ascendente · 121 cartas",
    detail: "ETB azul e rosa com Terapagos na arte.",
    alt: "Coleção Treinador Avançado Megaevolução Caos Ascendente, caixa azul e rosa com Terapagos",
    src: asset("produtos/treinador-avancado-cut.png"),
    orderLabel: "Coleção Treinador Avançado — Caos Ascendente",
  },
  {
    id: "blister-caos",
    featured: false,
    name: "Boosters blister",
    line: "Mega Evolução: Caos Ascendente · Copag",
    detail: "Blister com 4 packs.",
    alt: "Blister com quatro boosters Mega Evolução Caos Ascendente da Copag",
    src: asset("produtos/boosters-blister-cut.png"),
    orderLabel: "Boosters blister — Caos Ascendente",
  },
  {
    id: "tripack",
    featured: false,
    name: "Tripack",
    line: "Mega Evolução Equilíbrio Perfeito",
    detail: "Contém 19 cartas / 3 boosters + promo Makuhita.",
    alt: "Tripack Mega Evolução Equilíbrio Perfeito com três boosters e carta promo Makuhita",
    src: asset("produtos/tripack-cut.png"),
    orderLabel: "Tripack — Mega Evolução Equilíbrio Perfeito",
  },
  {
    id: "mewtwo-rocket",
    featured: false,
    name: "Coleção Mewtwo ex da Equipe Rocket",
    line: "Contém 40 cartas",
    detail: "Coleção com jumbo, promos e boosters da Equipe Rocket.",
    alt: "Coleção Mewtwo ex da Equipe Rocket com cartas visíveis na janela da caixa",
    src: asset("produtos/mewtwo-equipe-rocket-cut.png"),
    orderLabel: "Coleção Mewtwo ex da Equipe Rocket",
  },
  {
    id: "ferramentas-treinador",
    featured: false,
    name: "Ferramentas de Treinador",
    line: "94 cartas · Nível 3",
    detail: "Kit para montar baralho, com boosters e cartas de apoio.",
    alt: "Caixa Ferramentas de Treinador com Fezandipiti e 94 cartas",
    src: asset("produtos/ferramentas-treinador-cut.png"),
    orderLabel: "Ferramentas de Treinador",
  },
  {
    id: "sleeves-central",
    featured: false,
    name: "Sleeves Central Acessórios",
    line: "100 unidades · 63x88 mm",
    detail: "Shield Básico, cards padrão.",
    alt: "Pacote de 100 sleeves transparentes Central Acessórios Shield Básico",
    src: asset("produtos/sleeves-central-cut.png"),
    orderLabel: "Sleeves Central Acessórios 100 unidades",
  },
].map((item) => ({
  ...item,
  href: personalOrderUrl(item.orderLabel),
}));
